# Generated by Django 2.0.3 on 2018-09-12 00:43

import util.fields
import util.time
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("game", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created",
            field=util.fields.CreatedDateTimeField(
                blank=True, default=util.time.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="modified",
            field=util.fields.ModifiedDateTimeField(
                blank=True, default=util.time.now, editable=False
            ),
        ),
    ]
