# Generated by Django 2.0.3 on 2018-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181016_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_leaderboard_game',
            field=models.BooleanField(default=False),
        ),
    ]
