# Generated by Django 2.0.3 on 2018-11-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_game_is_leaderboard_game"),
        ("game", "0005_auto_20180923_2225"),
    ]

    operations = []
