# Generated by Django 2.0.3 on 2018-12-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("game", "0007_merge_20181124_0020")]

    operations = [
        migrations.AlterUniqueTogether(name="gamesnake", unique_together=set())
    ]
