# Generated by Django 2.0.3 on 2018-12-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_snake_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_leaderboard_game',
        ),
    ]
