# Generated by Django 2.0.3 on 2018-12-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_auto_20181213_0150"),
        ("game", "0009_remove_game_is_leaderboard_game"),
    ]

    operations = []
