# Generated by Django 2.0.10 on 2019-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_merge_20181221_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_turns_to_next_food_spawn',
            field=models.IntegerField(default=0),
        ),
    ]
