# Generated by Django 2.0.3 on 2018-06-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSnakeLeaderboard',
            fields=[
                ('user_snake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='snake.UserSnake')),
            ],
        ),
    ]
