# Generated by Django 2.0.3 on 2018-09-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("game", "0001_initial"), ("leaderboard", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="GameLeaderboard",
            fields=[
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="game.Game",
                    ),
                )
            ],
        )
    ]
