# Generated by Django 2.0.3 on 2018-10-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_gameleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersnakeleaderboard',
            name='mu',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usersnakeleaderboard',
            name='sigma',
            field=models.FloatField(null=True),
        ),
    ]
