# Generated by Django 2.0.3 on 2018-12-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_auto_20181220_2129"),
        ("leaderboard", "0004_auto_20181213_0150"),
    ]

    operations = []
