# Generated by Django 2.0.10 on 2019-02-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0002_snake")]

    operations = [
        migrations.RenameField(model_name="snake", old_name="user", new_name="profile")
    ]
