# Generated by Django 2.0.10 on 2019-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_game")]

    operations = [
        migrations.AddField(
            model_name="snake",
            name="is_public",
            field=models.BooleanField(default=False),
        )
    ]
