# Generated by Django 2.0.3 on 2018-06-30 18:10

import apps.authentication.models
from django.db import migrations, models
import util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    util.fields.ShortUUIDField(
                        max_length=128, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=39, unique=True)),
                ("email", models.CharField(max_length=512)),
            ],
            managers=[("objects", apps.authentication.models.UserManager())],
        )
    ]
