# Generated by Django 2.0.10 on 2019-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user", name="is_staff", field=models.BooleanField(default=False)
        )
    ]
