# Generated by Django 2.0.10 on 2019-02-04 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import util.fields
import util.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20190128_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('created', util.fields.CreatedDateTimeField(blank=True, default=util.time.now, editable=False)),
                ('modified', util.fields.ModifiedDateTimeField(blank=True, default=util.time.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
