# Generated by Django 2.0.3 on 2018-09-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180919_2157'),
        ('tournament', '0002_auto_20180907_1505'),
    ]

    operations = [
    ]
