# Generated by Django 2.0.3 on 2018-09-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tournament", "0003_merge_20180923_2223")]

    operations = [
        migrations.AlterModelOptions(name="teammember", options={}),
        migrations.AlterField(
            model_name="snaketournament",
            name="snake",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="snake.Snake"
            ),
        ),
    ]
