# Generated by Django 2.0.3 on 2018-11-01 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_auto_20180923_2225"),
        ("tournament", "0004_auto_20180923_2225"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatgame",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="game.Game",
            ),
        )
    ]
