# Generated by Django 2.0.3 on 2018-11-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tournament", "0005_heatgame_game")]

    operations = [
        migrations.AddField(
            model_name="heat",
            name="desired_games",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="heatgame",
            name="game",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="game.Game",
            ),
            preserve_default=False,
        ),
    ]
