# Generated by Django 2.0.3 on 2018-11-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0006_auto_20181123_2004"),
        ("tournament", "0003_auto_20181016_2142"),
    ]

    operations = []
