# Generated by Django 2.0.3 on 2018-11-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tournament", "0007_merge_20181124_0020")]

    operations = [
        migrations.CreateModel(
            name="TournamentGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_group",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.TournamentGroup",
            ),
            preserve_default=False,
        ),
    ]
