# Generated by Django 2.0.3 on 2018-12-10 18:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tournament', '0009_auto_20181210_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentGroup',
            new_name='Tournament',
        ),
    ]
