# Generated by Django 2.0.3 on 2018-12-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snake", "0001_initial"),
        ("tournament", "0011_auto_20181210_1854"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snaketournamentbracket",
            old_name="tournament",
            new_name="tournament_bracket",
        ),
        migrations.AlterUniqueTogether(
            name="snaketournamentbracket",
            unique_together={("snake", "tournament_bracket")},
        ),
    ]
