# Generated by Django 2.0.3 on 2019-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tournament", "0013_auto_20181210_2049")]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="single_snake_per_team",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("LO", "Locked"),
                    ("RE", "Registration"),
                    ("PR", "In Progress"),
                    ("JR", "Complete"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
    ]
