# Generated by Django 2.0.3 on 2019-01-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20190117_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakeheat',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Snake'),
        ),
    ]
