# Generated by Django 2.0.3 on 2019-01-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0016_auto_20190118_1525"),
        ("tournament", "0014_auto_20190125_0017"),
    ]

    operations = []
