# Generated by Django 2.0.10 on 2019-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tournament", "0017_merge_20190125_2025")]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("LO", "Locked"),
                    ("HI", "Hidden"),
                    ("RE", "Registration"),
                    ("PR", "In Progress"),
                    ("JR", "Complete"),
                ],
                default="LO",
                max_length=2,
            ),
        )
    ]
