# Generated by Django 2.0.10 on 2019-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tournament", "0018_auto_20190128_2225")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="can_register_in_tournaments",
            field=models.BooleanField(default=False),
        )
    ]
