# Generated by Django 2.0.10 on 2019-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20190128_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatgame',
            name='status',
            field=models.CharField(choices=[('UW', 'Unwatched'), ('W', 'Watching'), ('WD', 'Watched')], default='UW', max_length=2),
        ),
    ]
