# Generated by Django 2.0.10 on 2019-02-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0019_heatgame_status"),
        ("tournament", "0019_team_can_register_in_tournaments"),
    ]

    operations = []
