# Generated by Django 2.0.10 on 2019-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_merge_20190202_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='board_food',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='board_height',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='board_width',
            field=models.IntegerField(default=20),
        ),
    ]
