# Generated by Django 2.0.10 on 2019-02-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tournament", "0020_merge_20190202_0617")]

    operations = [migrations.RemoveField(model_name="team", name="snake")]
