# Generated by Django 2.0.10 on 2019-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tournament", "0021_remove_team_snake")]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="casting_uri",
            field=models.CharField(default="", max_length=1024),
        )
    ]
