# Generated by Django 2.0.10 on 2019-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_tournament_casting_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatgame',
            name='status',
            field=models.CharField(choices=[('UW', 'Not Casted Yet'), ('W', 'Casting'), ('WD', 'Casted')], default='UW', max_length=2),
        ),
    ]
