# Generated by Django 2.0.10 on 2019-02-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0021_auto_20190205_1854"),
        ("tournament", "0023_auto_20190205_1800"),
    ]

    operations = []
